apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::701703545554:role/EKSNodeInstanceRole
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::701703545554:role/service-role/codebuild-brain-tasks-build-service-role
      username: codebuild
      groups:
        - system:masters

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

